development:
  adapter: postgresql
  encoding: utf8
  database: speedop_development
  username: speedop
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: speedop_test
  username: speedop
  password:
